W7D1/UserAuth/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users
  resource :session, only: [:create, :destroy]
end

W7D1/UserAuth/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

W7D1/UserAuth/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint           not null, primary key
#  username        :string           not null
#  password_digest :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  session_token   :string           not null
#
class User < ApplicationRecord

    validates :username, presence: true
    validates :password_digest, presence: {message: 'Password can not be blank.'}
    validates :password, length: {minimum: 6, allow_nil: true}
    validates :session_token, presence: true, uniqueness: true
    after_initialize :ensure_session_token

    def password=(password)
        @password = password
        self.password_digest = BCrypt::Password.create(password)
    end

    def is_password?(password)
        BCrypt::Password.new(self.password_digest).is_password?(password)
    end

    def self.generate_session_token
        SecureRandom::urlsafe_base64(16)
    end

    def reset_session_token!
        self.session_token = self.class.generate_session_token
        self.save!
        self.session_token
    end

    def self.find_by_credentials(username, password)
        user = User.find_by(username: username)
        return nil if user.nil?
        user.is_password?(password) ? user : nil
    end

    attr_reader :password

    private
    def ensure_session_token
        self.session_token ||= self.class.generate_session_token
    end
end

W7D1/UserAuth/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    helper_method :current_user, :logged_in?

    def login!(user)
        @current_user = user
        session[:session_token] = user.reset_session_token
    end

    def logged_in?
        !!current_user
    end

    def current_user
        return nil if session[:session_token].nil?
        @current_user ||= User.find_by(session_token: session[:session_token])
    end

    def logout!
        current_user.try(:reset_session_token!)
        session[:session_token] = nil
        @current_user = nil
    end
end

W7D1/UserAuth/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def create
        user = User.find_by_credentials(
            params[:user][:username],
            params[:user][:password]
        )

        if user.nil?
            render json: 'Credentials were wrong'
        else
            login!(user)
            redirect_to user_url(user)
        end
    end

    def destroy
        logout!
        redirect_to new_session_url
    end

    def new
        
    end


end

W7D1/UserAuth/app/controllers/users_controller.rb
class UsersController < ApplicationController

    def create
        @user = User.new(user_params)

        if @user.save
            login!(@user)
            redirect_to user_url(@user)
        else
            render json: @user.errors.full_messages
        end
    end

    def new
        @user = User.new
        render :new
    end

    


    private
    
    def user_params
        params.require(:user).permit(:username, :password)
    end
end

W7D1/UserAuth/app/helpers/application_helper.rb
module ApplicationHelper
end

W7D1/UserAuth/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UserAuth</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <% if logged_in? %>
        <h2>Welcome <%=current_user.username  %> </h2>
    <% else %>

    <% end %>

    <% if !current_user.nil? %>
      <ul>
        <li>Logged in as: <%= current_user.username %></li>
        <li>
          <form action="<%= session_url %>" method="POST">
            <input type="hidden"
                  name="authenticity_token"
                  value="<%= form_authenticity_token %>">
            <input type="hidden" value="delete" name="_method" />
            <input type="submit" value="Logout" />
          </form>
        </li>
      </ul>
    <% end %>
    <%= yield %>
  </body>
</html>

W7D1/UserAuth/app/views/users/_form.html.erb
<% action = (user.persisted? ? user_url(user) : users_url) %>
<% method = user.persisted? ? "patch" : "post" %>
<% message = user.persisted? ? "Update User:" : "Create User:" %>

<form action="<%=action%>" method="post">
    <input name="_method" type="hidden" value="<%=method%>">
    <input name="authenticity_token" type="hidden" value="<%=form_authenticity_token%>">

    <label for="user_username">Username:</label>
    <input
        id="user_username"
        name="user[username]"
        type="text"
    > 

    <label for="user_password">Password:</label>
    <input
        id="user_password"
        name="user[password]"
        type="password"
    >

    <input type="submit" message=<%=message%>>

</form>

W7D1/UserAuth/app/views/users/new.html.erb
<h1>Create a new user:</h1>

<%= render "form", user: @user %>

W7D1/UserAuth/app/views/users/show.html.erb
<h1><%= @user.username %></h1>

<p>Hello, dear user!</p>